### ISSUE TITLE
Game crashes when installed

### ISSUE THREAD

**Issue by SimRacer918** [LucasWander/Assetto-Corsa-ERS-App#1]
Installed the app using content manager and manually but when I load in the game just crashes. Hopefully this can be fixed because I really like the idea of the app :)

**Comment by LucasWander** [comment]
Fixed on the new release

**Comment by SimRacer918** [comment]
Thanks for the update but unfortunately The game still crashes for me. I tried different versions of custom shaders patch but that didn't seem like the reason, I also tried to run base game assetto corsa but still with the same result.

https://imgur.com/UHLZakT

**Comment by SimRacer918** [comment]
> Thanks for the update but unfortunately The game still crashes for me. I tried different versions of custom shaders patch but that didn't seem like the reason, I also tried to run base game assetto corsa but still with the same result.
> 
> https://imgur.com/UHLZakT

Nvm, now it seem to work just fine. I guess i just did smt wrong, tnx for the mod ;)
